[package]
name = "muxy-server"
description = "The Muxy server executable"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
regex = "1"
notify = "8"
muxy-terminal = { path = "../muxy-terminal" }
getrandom = "0.3"
postcard = { version = "1", default-features = false, features = ["use-std"] }
muxy-protocol = { path = "../muxy-protocol" }
serde_json.workspace = true
log = { version = "0.4", features = ["std"] }
muxy-core = { path = "../muxy-core" }
serde = { version = "1", features = ["derive"] }
signal-hook = "0.4"
toml = "1.1"


[target.'cfg(target_os = "macos")'.dependencies]
libproc = "0.14.11"
