use muxy_core::prefs::SortMode;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Command {
    TogglePin(String),
    StartRename(String),
    OpenSymbolPicker(String),
    RemoveIcon(String),
    OpenColorPicker(String),
    ResetIconColor(String),
    PickLogo(String),
    RemoveLogo(String),
    ToggleWorktrees(String),
    ToggleWorktreeExpansion(String),
    SelectProject(String),
    SelectWorktree {
        project_id: String,
        worktree_id: String,
    },
    RefreshWorktrees(String),
    NewWorktree(String),
    RemoveWorktree {
        project_id: String,
        worktree_id: String,
    },
    CopyPath(String),
    CopyStatusPath(String),
    RevealStatusPath(String),
    RemoveProject(String),
    SelectWorkspaceGroup(Option<String>),
    SetProjectSort(SortMode),
    DeleteWorkspaceGroup(String),
    CreateWorkspaceGroup,
    RenameWorkspaceGroup(String),
    MoveProjectToWorkspace {
        project_id: String,
        group_id: String,
    },
    HideHome,
    OpenProjectPicker,
    NewTabLeft(String),
    NewTabRight(String),
    StartTabRename(String),
    ResetTabTitle(String),
    OpenTabColorPicker(String),
    ResetTabColor(String),
    ToggleTabPinned(String),
    CloseTab(String),
    CloseOtherTabs(String),
    CloseTabsToLeft(String),
    CloseTabsToRight(String),
    RunCommandShortcut(String),
    ApplyLayout(String),
    RestoreRecentlyRemoved(String),
    TerminalCopy(String),
    TerminalPaste(String),
    ToggleComposerBroadcast,
    SubmitComposerWithoutReturn,
    ToggleComposerClearAfterSending,
    ToggleComposerClearOnClose,
    OpenInIde(String),
    DismissOverlay,
}
