use super::Category;

pub(super) struct Setting {
    pub(super) id: &'static str,
    pub(super) label: &'static str,
    pub(super) description: &'static str,
    pub(super) category: Category,
    pub(super) section: &'static str,
}

pub(super) const SETTINGS: &[Setting] = &[
    Setting {
        id: "ai-commit-provider",
        label: "Commit provider",
        description: "AI CLI that drafts commit messages. Auto uses the first installed provider.",
        category: Category::Ai,
        section: "Commit and Push",
    },
    Setting {
        id: "ai-commit-prompt",
        label: "Commit prompt",
        description: "AI drafts only the commit message. You review it before Muxy commits every change and pushes. An empty prompt uses the default. Do not include secrets.",
        category: Category::Ai,
        section: "Commit and Push",
    },
    Setting {
        id: "ai-create-pr-provider",
        label: "Pull request provider",
        description: "AI CLI that drafts pull requests. Auto uses the first installed provider.",
        category: Category::Ai,
        section: "Create Pull Request",
    },
    Setting {
        id: "ai-create-pr-prompt",
        label: "Pull request prompt",
        description: "AI drafts the title, summary, branch name, and target branch. You review them before Muxy commits, pushes, and opens the pull request. An empty prompt uses the default.",
        category: Category::Ai,
        section: "Create Pull Request",
    },
    Setting {
        id: "voice-auto-send",
        label: "Send after recording",
        description: "Press Return after inserting standalone voice dictation into the terminal.",
        category: Category::Composer,
        section: "Voice",
    },
    Setting {
        id: "composer-language",
        label: "Dictation language",
        description: "Choose an installed on-device speech language.",
        category: Category::Composer,
        section: "Voice",
    },
    Setting {
        id: "composer-clear-after",
        label: "Clear after sending",
        description: "Clear the draft only after every terminal confirms delivery.",
        category: Category::Composer,
        section: "Behavior",
    },
    Setting {
        id: "composer-clear-close",
        label: "Clear on close",
        description: "Discard the draft when closing Composer or switching projects.",
        category: Category::Composer,
        section: "Behavior",
    },
    Setting {
        id: "composer-images",
        label: "Image submission",
        description: "Paste image contents into compatible terminal apps or insert the saved image path.",
        category: Category::Composer,
        section: "Behavior",
    },
    Setting {
        id: "composer-font",
        label: "Composer font",
        description: "Font family used for composing text.",
        category: Category::Composer,
        section: "Text",
    },
    Setting {
        id: "composer-line-height",
        label: "Composer line height",
        description: "Line spacing from 1.1 to 2.0.",
        category: Category::Composer,
        section: "Text",
    },
    Setting {
        id: "quick-enabled",
        label: "Enable Quick Terminal",
        description: "Show a persistent home-directory shell with a shortcut.",
        category: Category::QuickTerminal,
        section: "General",
    },
    Setting {
        id: "quick-shortcut",
        label: "Open Quick Terminal",
        description: "Record a system-wide shortcut to open Quick Terminal.",
        category: Category::QuickTerminal,
        section: "Shortcut",
    },
    Setting {
        id: "quick-size",
        label: "Terminal size",
        description: "Width 480–1200; height 280–800 pixels.",
        category: Category::QuickTerminal,
        section: "Size",
    },
    Setting {
        id: "quick-transparency",
        label: "Terminal transparency",
        description: "Transparency of the terminal background.",
        category: Category::QuickTerminal,
        section: "Appearance",
    },
    Setting {
        id: "quick-blur",
        label: "Background vibrancy",
        description: "Vibrancy of the glass background.",
        category: Category::QuickTerminal,
        section: "Appearance",
    },
    Setting {
        id: "close-behavior",
        label: "When closing tabs or panes",
        description: "Close sessions unused by other panes, or detach to keep them running and reopen them from Existing Terminals.",
        category: Category::General,
        section: "Closing terminals",
    },
    Setting {
        id: "confirm-process",
        label: "Confirm before closing a running process",
        description: "Ask before ending a running command. Detaching never requires confirmation.",
        category: Category::General,
        section: "Closing terminals",
    },
    Setting {
        id: "width",
        label: "Default window width",
        description: "Width in pixels for a new workspace window when no saved bounds exist.",
        category: Category::General,
        section: "Window size",
    },
    Setting {
        id: "height",
        label: "Default window height",
        description: "Height in pixels for a new workspace window when no saved bounds exist.",
        category: Category::General,
        section: "Window size",
    },
    Setting {
        id: "light-theme",
        label: "Light theme",
        description: "Colors for the interface and terminals when macOS uses light appearance.",
        category: Category::Appearance,
        section: "Themes",
    },
    Setting {
        id: "dark-theme",
        label: "Dark theme",
        description: "Colors for the interface and terminals when macOS uses dark appearance.",
        category: Category::Appearance,
        section: "Themes",
    },
    Setting {
        id: "sidebar",
        label: "Expand sidebar",
        description: "Show project names alongside their icons in the workspace sidebar.",
        category: Category::Appearance,
        section: "Interface",
    },
    Setting {
        id: "status-bar",
        label: "Show status bar",
        description: "Show connection and terminal information at the bottom of the workspace.",
        category: Category::Appearance,
        section: "Interface",
    },
    Setting {
        id: "sidebar-collapsed-style",
        label: "Collapsed sidebar style",
        description: "Show project icons or hide the sidebar in Project Focused. Tab Focused always hides it when collapsed.",
        category: Category::Appearance,
        section: "Interface",
    },
    Setting {
        id: "sidebar-vibrancy",
        label: "Sidebar vibrancy",
        description: "Use a translucent macOS background while the sidebar is expanded.",
        category: Category::Appearance,
        section: "Interface",
    },
    Setting {
        id: "sidebar-vibrancy-level",
        label: "Sidebar vibrancy level",
        description: "How much of the macOS background effect shows through the theme color, from 0 to 100. Collapsed sidebars stay solid.",
        category: Category::Appearance,
        section: "Interface",
    },
    Setting {
        id: "auto-expand-worktrees",
        label: "Expand worktrees when switching projects",
        description: "Reveal worktrees when selecting a project in Project Focused.",
        category: Category::Appearance,
        section: "Interface",
    },
    Setting {
        id: "worktree-order",
        label: "Order worktrees by recent use",
        description: "List recently selected worktrees first, after the primary worktree.",
        category: Category::Appearance,
        section: "Interface",
    },
    Setting {
        id: "worktree-unread",
        label: "Show unread worktree indicators",
        description: "Show unread completion counts beside worktrees.",
        category: Category::Appearance,
        section: "Interface",
    },
    Setting {
        id: "extension-sidebar",
        label: "Active sidebar",
        description: "Show an enabled extension's sidebar in place of the built-in one.",
        category: Category::Appearance,
        section: "Interface",
    },
    Setting {
        id: "font-family",
        label: "Font family",
        description: "The typeface used to render text in every terminal pane.",
        category: Category::Terminal,
        section: "Text",
    },
    Setting {
        id: "font-size",
        label: "Font size (points)",
        description: "Default terminal text size. Individual panes can still be zoomed independently.",
        category: Category::Terminal,
        section: "Text",
    },
    Setting {
        id: "adjust-cell-height",
        label: "Cell height adjustment (pixels or %)",
        description: "Add space between terminal lines using pixels or a percentage, such as 10%.",
        category: Category::Terminal,
        section: "Text",
    },
    Setting {
        id: "copy-on-select",
        label: "Copy on select",
        description: "Copy selected terminal text to the clipboard as soon as you finish selecting.",
        category: Category::Terminal,
        section: "Behavior",
    },
    Setting {
        id: "directory",
        label: "New pane directory",
        description: "Start new splits in the project folder or the current pane's working directory.",
        category: Category::Terminal,
        section: "Behavior",
    },
    Setting {
        id: "ghostty-configuration",
        label: "Ghostty configuration",
        description: "Edit ghostty.conf to customize terminal appearance and key aliases such as Shift+Enter. Save the file, then reload to apply changes.",
        category: Category::Terminal,
        section: "Configuration",
    },
    Setting {
        id: "terminal-configuration-warnings",
        label: "Configuration warnings",
        description: "Unsupported Ghostty options in ghostty.conf are ignored.",
        category: Category::Terminal,
        section: "Configuration",
    },
    Setting {
        id: "server",
        label: "Current device",
        description: "Manage the local server that keeps your terminal sessions running.",
        category: Category::Server,
        section: "Connection",
    },
    Setting {
        id: "default-shell",
        label: "Default shell (executable path)",
        description: "Shell for new sessions. Leave empty to use $SHELL, falling back to /bin/zsh.",
        category: Category::Server,
        section: "Sessions",
    },
    Setting {
        id: "history-budget",
        label: "History budget per session (MiB)",
        description: "Retained terminal history, from 0 to 65536 MiB. Saved-history changes take effect at the next server start.",
        category: Category::Server,
        section: "Sessions",
    },
    Setting {
        id: "shell-integration",
        label: "Shell integration",
        description: "Enable working-directory tracking and prompt navigation in new sessions.",
        category: Category::Server,
        section: "Sessions",
    },
    Setting {
        id: "Stop Server",
        label: "Stop Server",
        description: "End all sessions on this device and stop the server. A confirmation is required.",
        category: Category::Server,
        section: "Server control",
    },
    Setting {
        id: "Restart Server",
        label: "Restart Server",
        description: "End all sessions and start the server again. Saved terminal records are preserved.",
        category: Category::Server,
        section: "Server control",
    },
];

pub(super) fn setting(id: &str) -> Option<&'static Setting> {
    SETTINGS.iter().find(|setting| setting.id == id)
}
