#[cfg(feature = "application")]
pub mod composer;
#[cfg(feature = "application")]
pub mod dropped_paths;
#[cfg(feature = "application")]
pub mod environment;
#[cfg(feature = "application")]
pub mod fold;
#[cfg(feature = "application")]
pub mod migration;
#[cfg(feature = "application")]
pub mod navigation;
#[cfg(feature = "application")]
pub mod notifications;
#[cfg(feature = "application")]
pub mod prefs;
#[cfg(feature = "application")]
pub mod quick_terminal;
#[cfg(feature = "application")]
pub mod repository_ai;
#[cfg(feature = "application")]
pub mod settings_catalog;
#[cfg(feature = "application")]
pub mod shortcuts;
#[cfg(feature = "application")]
pub mod store;
pub mod terminal_activity;
pub mod terminal_launch;
#[cfg(feature = "application")]
pub mod workspace;
#[cfg(feature = "application")]
pub mod workspace_store;
