build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

processors:
  active: true

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'

complexity:
  active: true
  LongMethod:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  ComplexCondition:
    active: true
    threshold: 6
  ComplexInterface:
    active: false
  CyclomaticComplexMethod:
    active: false

empty-blocks:
  active: true

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: false

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
    excludes: ['**/test/**', '**/androidTest/**']
  TopLevelPropertyNaming:
    active: false
  ConstructorParameterNaming:
    active: true
  ClassNaming:
    active: true
  PackageNaming:
    active: false
  MatchingDeclarationName:
    active: false

performance:
  active: true
  SpreadOperator:
    active: false

potential-bugs:
  active: true
  UnreachableCode:
    active: true

style:
  active: true
  WildcardImport:
    active: false
  MaxLineLength:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  UnusedPrivateMember:
    active: false
  UnusedPrivateProperty:
    active: false
  ForbiddenComment:
    active: false
  NewLineAtEndOfFile:
    active: true
  UnnecessaryAbstractClass:
    active: false
  DataClassContainsFunctions:
    active: false
  UseDataClass:
    active: false
  ThrowsCount:
    active: false
